// <auto-generated>
// Generated from models/weaven-debugger.als by als2cs.
// DO NOT EDIT — re-run `als2cs` to regenerate.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace Weaven.Generated
{
    // ── Identity types ──────────────────────────────────────────────────

    public readonly record struct SmId(uint Value);
    public readonly record struct StateId(uint Value);
    public readonly record struct TransitionId(uint Value);
    public readonly record struct PortId(uint Value);
    public readonly record struct ConnectionId(uint Value);
    public readonly record struct InteractionRuleId(uint Value);
    public readonly record struct Tick(ulong Value);
    public readonly record struct Label(string Value);
    public readonly record struct EvalValue(double Value);

    // ── Enumerations ────────────────────────────────────────────────────

    public enum Phase
    {
        PhaseInput,
        PhaseEvaluate,
        PhaseExecute,
        PhasePropagate,
        PhaseLifecycle,
        PhaseOutput,
    }

    public enum EdgeKind
    {
        EdgeStatic,
        EdgeSpatial,
        EdgeIR,
    }

    public enum ExprKind
    {
        ExprLit,
        ExprCtxRef,
        ExprSigRef,
        ExprTableRef,
        ExprBinOp,
        ExprNotOp,
        ExprIfOp,
        ExprPortRecv,
    }

    public sealed record GraphNode(
        SmId Sm,
        StateId? ActiveState
    );

    /// <summary>Invariant: NoSelfLoop</summary>
    public sealed record GraphEdge(
        GraphNode EdgeSource,
        GraphNode EdgeTarget,
        EdgeKind Kind,
        ConnectionId? ConnectionId
    );

    /// <summary>Invariant: EdgesReferenceGraphNodes</summary>
    /// <summary>Invariant: UniqueSmPerNode</summary>
    public sealed record TopologyGraph(
        IReadOnlySet<GraphNode> Nodes,
        IReadOnlySet<GraphEdge> Edges
    );

    /// <summary>Invariant: NoCyclicEvalTree</summary>
    public sealed record EvalTreeNode(
        ExprKind ExprKind,
        Label Label,
        EvalValue Value,
        IReadOnlyList<EvalTreeNode> Children
    );

    public sealed record ContextSnapshot(
        IReadOnlySet<ContextEntry> Fields
    );

    public sealed record ContextEntry(
        Label FieldName,
        EvalValue FieldValue
    );

    public sealed record SignalSnapshot(
        IReadOnlySet<ContextEntry> SignalFields
    );

    public sealed record GuardInspectionResult(
        TransitionId Transition,
        bool Fired,
        ContextSnapshot ContextAtEval,
        SignalSnapshot? SignalAtEval,
        EvalTreeNode ExprTree
    );

    /// <summary>Invariant: CursorRange</summary>
    public sealed record TickCursor(
        int Current,
        int MaxTick
    );

    public sealed record FilterConfig(
        IReadOnlySet<SmId> VisibleSms,
        IReadOnlySet<ConnectionId> VisibleConnections,
        IReadOnlySet<Phase> VisiblePhases
    );

    /// <summary>Invariant: SnapshotNonEmpty</summary>
    public sealed record DebugSession(
        IReadOnlyList<WorldSnapshot> Snapshots,
        TickCursor Cursor,
        SmId? SelectedSm,
        IReadOnlyList<TraceEvent> Trace,
        TopologyGraph Topology,
        FilterConfig FilterCfg
    );

    public sealed record TickResult(
        IReadOnlyList<TraceEvent> TraceEvents,
        IReadOnlySet<StateChange> StateChanges
    );

    public sealed record StateChange(
        SmId SmId,
        StateId FromState,
        StateId ToState
    );

    public sealed record WorldState(
        IReadOnlySet<SmStateEntry> SmStates
    );

    public sealed record SmStateEntry(
        SmId SmId,
        StateId ActiveState
    );

    public abstract record TraceEvent;

    public sealed record GuardEvaluated(
        Tick Tick,
        Phase Phase,
        TransitionId Transition,
        SmId SmId,
        bool Result
    ) : TraceEvent;

    public sealed record IrMatched(
        Tick Tick,
        Phase Phase,
        InteractionRuleId RuleId,
        IReadOnlySet<SmId> Participants
    ) : TraceEvent;

    public sealed record TransitionFired(
        Tick Tick,
        Phase Phase,
        TransitionId Transition,
        SmId SmId,
        StateId FromState,
        StateId ToState
    ) : TraceEvent;

    public sealed record SignalEmitted(
        Tick Tick,
        Phase Phase,
        SmId SmId,
        PortId Port,
        SmId? Target
    ) : TraceEvent;

    public sealed record CascadeStep(
        Tick Tick,
        Phase Phase,
        int Depth,
        int QueueSize
    ) : TraceEvent;

    public sealed record PipelineFiltered(
        Tick Tick,
        Phase Phase,
        ConnectionId? Connection,
        SmId SmId,
        PortId Port
    ) : TraceEvent;

    public sealed record WorldSnapshot();

}
