/**
 * Golden file tests — verify that the TS normalizer layer correctly handles
 * the ACTUAL Rust serde JSON output format.
 *
 * These fixtures are generated by:
 *   cargo test -p weaven-debugger-core --test golden_fixtures -- --ignored
 *
 * If these tests fail, it means the Rust serialization format changed
 * and the TS normalizer needs updating (or vice versa).
 */

import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync } from "fs";
import { resolve } from "path";
import { createCommands, type TauriInvoke } from "../commands";
import { useDebugStore } from "../stores/debugStore";

function loadFixture(name: string): any {
  const path = resolve(__dirname, "fixtures", name);
  return JSON.parse(readFileSync(path, "utf-8"));
}

beforeEach(() => {
  useDebugStore.setState({
    loaded: false,
    currentTick: 0,
    maxTick: 0,
    topology: null,
    traceEvents: [],
    selectedSmId: null,
    cascadeIndex: 0,
    selectedTraceIndex: null,
    filterConfig: { hiddenSmIds: new Set(), hiddenPhases: new Set() },
  });
});

describe("golden files — fire tick result normalization", () => {
  it("normalizes real Rust TraceEvent JSON into store-compatible format", async () => {
    const raw = loadFixture("fire_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const state = useDebugStore.getState();
    expect(state.currentTick).toBe(1);
    expect(state.loaded).toBe(true);
    expect(state.traceEvents.length).toBeGreaterThan(0);
  });

  it("all trace events have kind field after normalization", async () => {
    const raw = loadFixture("fire_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const events = useDebugStore.getState().traceEvents;
    for (const e of events) {
      expect(e).toHaveProperty("kind");
      expect(typeof (e as any).kind).toBe("string");
    }
  });

  it("GuardEvaluated events have smId as object with inner", async () => {
    const raw = loadFixture("fire_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const guards = useDebugStore.getState().traceEvents
      .filter((e: any) => e.kind === "GuardEvaluated");
    expect(guards.length).toBeGreaterThan(0);

    for (const g of guards) {
      const ge = g as any;
      expect(ge.smId).toHaveProperty("inner");
      expect(typeof ge.smId.inner).toBe("number");
      expect(ge.transition).toHaveProperty("inner");
      expect(typeof ge.result).toBe("boolean");
    }
  });

  it("TransitionFired events have fromState/toState as objects", async () => {
    const raw = loadFixture("fire_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const fired = useDebugStore.getState().traceEvents
      .filter((e: any) => e.kind === "TransitionFired");
    expect(fired.length).toBeGreaterThan(0);

    for (const f of fired) {
      const tf = f as any;
      expect(tf.fromState).toHaveProperty("inner");
      expect(tf.toState).toHaveProperty("inner");
      expect(tf.smId).toHaveProperty("inner");
    }
  });

  it("SignalEmitted events have target as object with inner", async () => {
    const raw = loadFixture("fire_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const emitted = useDebugStore.getState().traceEvents
      .filter((e: any) => e.kind === "SignalEmitted");
    expect(emitted.length).toBeGreaterThan(0);

    for (const e of emitted) {
      const se = e as any;
      expect(se.smId).toHaveProperty("inner");
      expect(se.port).toHaveProperty("inner");
      expect(se.target).toHaveProperty("inner");
    }
  });

  it("CascadeStep events have depth and queueSize as numbers", async () => {
    const raw = loadFixture("fire_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const cascade = useDebugStore.getState().traceEvents
      .filter((e: any) => e.kind === "CascadeStep");
    expect(cascade.length).toBeGreaterThan(0);

    for (const c of cascade) {
      const cs = c as any;
      expect(typeof cs.depth).toBe("number");
      expect(typeof cs.queueSize).toBe("number");
    }
  });

  it("PipelineFiltered events have connection as object", async () => {
    const raw = loadFixture("fire_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const filtered = useDebugStore.getState().traceEvents
      .filter((e: any) => e.kind === "PipelineFiltered");
    // May or may not exist depending on intensity values.
    for (const f of filtered) {
      const pf = f as any;
      expect(pf.smId).toHaveProperty("inner");
      if (pf.connection) {
        expect(pf.connection).toHaveProperty("inner");
      }
    }
  });

  it("phase values are short strings (Evaluate/Execute/Propagate)", async () => {
    const raw = loadFixture("fire_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const validPhases = new Set(["Input", "Evaluate", "Execute", "Propagate", "Lifecycle", "Output"]);
    for (const e of useDebugStore.getState().traceEvents) {
      const phase = (e as any).phase;
      expect(validPhases.has(phase), `Invalid phase "${phase}" in ${(e as any).kind}`).toBe(true);
    }
  });

  it("state_changes are normalized to stateChanges", async () => {
    const raw = loadFixture("fire_tick_result.json");
    // The raw has state_changes (snake_case).
    expect(raw).toHaveProperty("state_changes");

    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);
    const result = await cmds.tick();
    // Result should not crash — stateChanges is used internally.
    expect(useDebugStore.getState().currentTick).toBe(1);
  });
});

describe("golden files — fire topology normalization", () => {
  it("loads topology into store via getTopology", async () => {
    const raw = loadFixture("fire_topology.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.getTopology();

    const topo = useDebugStore.getState().topology;
    expect(topo).not.toBeNull();
    expect(topo!.nodes.length).toBe(3);
    expect(topo!.edges.length).toBe(2);
  });

  it("topology node sm_id is accessible (plain number or wrapped)", async () => {
    const raw = loadFixture("fire_topology.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.getTopology();

    const topo = useDebugStore.getState().topology!;
    for (const node of topo.nodes) {
      // sm_id from Rust is a plain number.
      const id = typeof node.sm_id === "number" ? node.sm_id : (node.sm_id as any).inner;
      expect(typeof id).toBe("number");
      expect(id).toBeGreaterThan(0);
    }
  });
});

describe("golden files — parry scenario", () => {
  it("parry tick result normalizes correctly", async () => {
    const raw = loadFixture("parry_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const events = useDebugStore.getState().traceEvents;
    expect(events.length).toBeGreaterThan(0);
    // All events should have kind.
    expect(events.every((e: any) => typeof e.kind === "string")).toBe(true);
  });

  it("GuardEvaluated context_snapshot is preserved", async () => {
    const raw = loadFixture("parry_tick_result.json");
    const mockInvoke: TauriInvoke = async () => raw;
    const cmds = createCommands(mockInvoke);

    await cmds.tick();

    const guards = useDebugStore.getState().traceEvents
      .filter((e: any) => e.kind === "GuardEvaluated");

    const withCtx = guards.filter((g: any) => g.contextSnapshot != null);
    expect(withCtx.length).toBeGreaterThan(0);
  });
});
